from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

DATASET_PATH = str(BASE_DIR / "dataset" / "orl_faces")
GENERATED_PATH = str(BASE_DIR / "generated")

IMAGE_WIDTH = 92
IMAGE_HEIGHT = 112

IMAGE_SIZE = (IMAGE_WIDTH, IMAGE_HEIGHT)

N_COMPONENTS = 50
EIGENFACE_TOP_K = 16

FACE_CASCADE_SCALE_FACTOR = 1.1
FACE_CASCADE_MIN_NEIGHBORS = 5
FACE_CASCADE_MIN_SIZE = (60, 60)

UNKNOWN_FACE_THRESHOLD = 6054.75